# Generated by Django 3.1.3 on 2020-12-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201201_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='size_l',
            new_name='size_lg',
        ),
    ]
