# Generated by Django 3.1.3 on 2021-01-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210118_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='product_id',
            new_name='product',
        ),
    ]
