# Generated by Django 3.1.3 on 2021-01-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20210119_1400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
