# Generated by Django 3.1.3 on 2021-01-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_delete_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_reviews',
            field=models.IntegerField(null=True),
        ),
    ]
