# Generated by Django 3.1.3 on 2021-01-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_number_of_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number_of_reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
